packages:
    - packages/core
    - packages/redis
    - packages/middleware/*
    - packages/benchmarks
    - packages/site
    - examples/*

overrides:
    esbuild: '>=0.25.0'

onlyBuiltDependencies: '["lefthook", "esbuild"]'
